In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)
print(cumulative_sum)  # [ 1  3  6 10 15]

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
cumulative_sum_axis0 = np.cumsum(arr2d, axis=0)
print(cumulative_sum_axis0)
# [[ 1  2  3]
#  [ 5  7  9]
#  [12 15 18]]

cumulative_sum_axis1 = np.cumsum(arr2d, axis=1)
print(cumulative_sum_axis1)
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

[ 1  3  6 10 15]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
