In [1]:
from scipy import sparse
import pandas as pd
import numpy as np

data1 = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
         'Age': [25, 30, 35, 40]}

data2 = {'Country': ['USA', 'Canada', 'UK', 'USA'],
         'Gender': ['Female', 'Male', 'Male', 'Male']}
         
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# 데이터프레임을 2차원 배열로 변환
df_combined = pd.concat([df1, df2], axis=1)
print(df_combined)

      Name  Age Country  Gender
0    Alice   25     USA  Female
1      Bob   30  Canada    Male
2  Charlie   35      UK    Male
3    David   40     USA    Male


In [11]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
combined_encoded = encoder.fit_transform(df_combined)

combined_encoded.toarray()

array([[1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.]])

In [12]:
data3 = {'University': ['A', 'B', 'C', 'D'],
         'Country': ['1', '2', '3', '4']}
         
df3 = pd.DataFrame(data3)

In [13]:
from scipy import sparse

all_data_sprs = sparse.hstack([
    sparse.csr_matrix(df3), combined_encoded
], format='csr')

# 처음에 hstack 에서는 object type 을 지원하지 않기에 에러가 났었다. 

# 왜 에러나는지 이유를 못찾겠다 ㅠㅍ 

TypeError: no supported conversion for types: (dtype('O'),)

In [16]:
from scipy.sparse import coo_matrix, hstack

A = coo_matrix([[1, 2], [3, 4]])
B = coo_matrix([[5], [6]])
print(hstack([A,B], format='csr').toarray())

[[1 2 5]
 [3 4 6]]
