In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

fruits = ['사과','블루베리','바나나','귤','블루베리','바나나','바나나','사과']

# 레이블 인코더, 원-핫 인코더 생성
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

# 레이블 인코딩 적용(문자 데이터 -> 숫자 데이터)
fruits_label_encoded = label_encoder.fit_transform(fruits)
# 원-핫 인코딩 적용
fruits_onehot_encoded = onehot_encoder.fit_transform(fruits_label_encoded.reshape(-1,1))

print('원-핫 인코딩 적용 후 데이터:\n', fruits_onehot_encoded.toarray())
print('원-핫 인코딩 적용 후 데이터 (CSR 형태임):\n', fruits_onehot_encoded)

원-핫 인코딩 적용 후 데이터:
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
원-핫 인코딩 적용 후 데이터 (CSR 형태임):
   (0, 3)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 2)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 3)	1.0


In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# 전체 데이터를 set 처럼 중복 제거후에 one-hot encoder 로 만든다.
data = {
    'year': [2016, 2017, 2018,2016,2016],
    'GDP rate': [28, 31, 30,30,2016],
    'GDP' : ['1.637M', '1.73M', '1.83M','1.99M','1.22M']
}

df = pd.DataFrame(data)

encoder = OneHotEncoder()
all_data_encoded = encoder.fit_transform(df)

all_data_encoded.toarray()

array([[1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])